version: '3.6'

services:
  youappz:
    build:
      context: .
    image: youappz
    container_name: youappz
    restart: 'always'
    volumes:
      - ./:/usr/src
      - ~/.aws/:/root/.aws:ro
      - node_modules:/usr/src/node_modules
    env_file:
      - .env
volumes:
  node_modules:
