blank_issues_enabled: true
version: 2.1
contact_links:
  - name: 📖 Youappz Documentation
    url: https://docs.youappz.com/
    about: Documentation about Youappz  
  - name: 📖 Ask a question
    url: https://github.com/youappz/youappz/discussions
    about: Ask questions and discuss ideas with other community members
