name: Process Examples

on:
  push:
    branches:
      - master
    paths:
      - 'examples/**'

env:  
  DO_NOT_TRACK: 1
  CLOUDFLARE_R2_ENDPOINT_URL: https://39776f06cb737bb0a935594aff7abad1.r2.cloudflarestorage.com
  CLOUDFLARE_R2_BUCKET_NAME: getappz

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find deleted examples
        id: find-deleted
        run: |
          git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.sha }} | \
            awk -F/ '!/^\./ && /^examples/ {print $2}' | \
            sort -u | \
            xargs -I{} echo "examples/{}" > deleted_examples.txt
          if [ ! -s deleted_examples.txt ]; then
            echo "No deleted folders found."
          fi
        shell: bash

      - name: Delete example archives from R2
        run: |
          if [ -f deleted_examples.txt ]; then
            while read -r folder; do
              folder_name=$(basename "$folder")
              aws s3api delete-object \
                --endpoint-url $CLOUDFLARE_R2_ENDPOINT_URL \
                --bucket $CLOUDFLARE_R2_BUCKET_NAME \
                --key "examples/$folder_name.tar.gz"
            done < deleted_examples.txt
          else
            echo "No deleted_examples.txt file found. Skipping deletion step."
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "auto"

      - name: Find modified examples
        id: find-changed
        run: |
          git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.sha }} | \
            awk -F/ '!/^\./ && /^examples/ {print $2}' | \
            sort -u | \
            xargs -I{} echo "examples/{}" > modified_examples.txt
          if [ ! -s modified_examples.txt ]; then
            echo "No changes in example folders."
            exit 1
          fi
        shell: bash

      - name: Compress changed folders
        run: |
          if [ -f modified_examples.txt ]; then
            mkdir archives
            while read -r folder; do
              folder_name=$(basename "$folder")
              tar -czvf "archives/$folder_name.tar.gz" -C "$(dirname "$folder")" "$folder_name"
            done < modified_examples.txt
           else
            echo "No modified_examples.txt file found. Skipping Compression step."
          fi
        shell: bash

      - name: Generate examples list.json
        run: |                    
          find examples -mindepth 1 -maxdepth 1 -type d  -exec basename {} \; | jq -R '{"name": .}' | jq -s . > archives/list.json
        shell: bash

      - name: Upload example archives to R2
        run: |
          for file in archives/*.*; do
            aws s3api put-object \
              --endpoint-url $CLOUDFLARE_R2_ENDPOINT_URL \
              --bucket $CLOUDFLARE_R2_BUCKET_NAME \
              --key examples/$(basename "$file") \
              --body "$file"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "auto"      