name: Process Examples
on:
  push:
    paths:
      - 'examples/**'
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Find changed folders
        id: find-changed
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | \
            awk -F/ '{print $1}' | \
            sort -u | \
            grep -v '/\.' | \
            xargs -I{} echo "examples/{}" > changed_folders.txt
          if [ ! -s changed_folders.txt ]; then
            echo "No changes in example folders."
            exit 1
          fi
        shell: bash
      - name: Compress changed folders
        run: |
          while read -r folder; do
            tar -czvf "$folder.tar.gz" "$folder"
          done < changed_folders.txt
        shell: bash