name: Compress Changed Folders
on:
  push:
    paths:
      - 'examples/**'
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Find changed folders
        id: find-changed
        run: |
          git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.sha }} | \
            awk -F/ '!/^\./ && /^examples/ {print $2}' | \
            sort -u | \
            xargs -I{} echo "examples/{}" > changed_folders.txt
          if [ ! -s changed_folders.txt ]; then
            echo "No changes in example folders."
            exit 1
          fi
        shell: bash
      - name: Compress changed folders
        run: |
          while read -r folder; do
            folder_name=$(basename "$folder")
            tar -czvf "$folder_name.tar.gz" -C "$(dirname "$folder")" "$folder_name"
          done < changed_folders.txt
          ls -lahs
        shell: bash