name: Process Examples

on:
  push:
    branches:
      - master
    paths:
      - 'examples/**'

env:  
  DO_NOT_TRACK: 1
  CLOUDFLARE_R2_ENDPOINT_URL: https://39776f06cb737bb0a935594aff7abad1.r2.cloudflarestorage.com
  CLOUDFLARE_R2_BUCKET_NAME: getappz

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Find changed folders
        id: find-changed
        run: |
          git diff --name-only --diff-filter=d ${{ github.event.before }} ${{ github.sha }} | \
            awk -F/ '!/^\./ && /^examples/ {print $2}' | \
            sort -u | \
            xargs -I{} echo "examples/{}" > changed_folders.txt
          if [ ! -s changed_folders.txt ]; then
            echo "No changes in example folders."
            exit 1
          fi
        shell: bash

      - name: Compress changed folders
        run: |
          while read -r folder; do
            folder_name=$(basename "$folder")
            tar -czvf "examples/$folder_name.tar.gz" -C "$(dirname "$folder")" "$folder_name"
          done < changed_folders.txt
          ls -lahs
        shell: bash

      - name: Generate examples list.json
        run: |
          mkdir archives
          touch archives/list.json
          echo '[' > archives/list.json
          find examples -type d -exec basename {} \; | awk '{print "  {\n    \"name\": \"" $0 "\"\n  },"}' >> list.json
          sed -i '$ s/,$//' list.json
          echo ']' >> archives/list.json
        shell: bash

      - name: Upload example archives to R2
        run: |
          for file in archives/*.*; do
            aws s3api put-object \
              --endpoint-url $CLOUDFLARE_R2_ENDPOINT_URL \
              --bucket $CLOUDFLARE_R2_BUCKET_NAME \
              --key examples/$(basename "$file") \
              --body "$file"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "auto"

      - name: Find deleted folders
        id: find-deleted
        run: |
          git diff --name-only --diff-filter=D ${{ github.event.before }} ${{ github.sha }} | \
            awk -F/ '!/^\./ && /^examples/ {print $2}' | \
            sort -u | \
            xargs -I{} echo "examples/{}" > deleted_folders.txt
          if [ ! -s deleted_folders.txt ]; then
            echo "No deleted folders found."
          fi
        shell: bash

      - name: Delete example archives from R2
        run: |
          if [ -f deleted_folders.txt ]; then
            while read -r folder; do
              folder_name=$(basename "$folder")
              aws s3api delete-object \
                --endpoint-url $CLOUDFLARE_R2_ENDPOINT_URL \
                --bucket $CLOUDFLARE_R2_BUCKET_NAME \
                --key "examples/$folder_name.tar.gz"
            done < deleted_folders.txt
          else
            echo "No deleted_folders.txt file found. Skipping deletion step."
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "auto"